### ISSUE TITLE
第62条有一点写的不对

### ISSUE THREAD

**Issue by Barenboim** [chanchann/workflow_annotation#1]
"所以server task的生命会持续到series结束，本质是在于它还没执行完回复"
这个表述不对，任何task生命周期都是到callback结束。server task也不例外。server task callback也不代表series结束，因为完全可以继续push_back任务，例如：
~~~cpp
void server_task_callback(WFHttpTask *server_task)
{
    WFHttpTask *report_task = WFTaskFactory::create_http_task(...);
    ....
    **server_task << report_task;
}
~~~
server task在series为空的时候回复，但回复完callback依然可以向series里添加任务。显然server task生命周期和series不一样。

**Comment by chanchann** [comment]
https://github.com/chanchann/workflow_annotation/blob/main/src_analysis/faq_62.md

已经重新分析并修改

**Comment by Barenboim** [comment]
哈哈，其实最好只强调生命周期，任何task生命周期都是到callback结束，callback之后就不能再访问了。而内部实际delete task的时机，不一定是callback之后立刻进行。但这个和用户的使用无关，callback之后不能再使用task。

**Comment by chanchann** [comment]
为什么这里delete task不会立即执行呢

**Comment by chanchann** [comment]
```cpp
virtual SubTask *done()
{
	SeriesWork *series = series_of(this);

	if (this->state == WFT_STATE_SYS_ERROR && this->error < 0)
	{
		this->state = WFT_STATE_SSL_ERROR;
		this->error = -this->error;
	}

	if (this->callback)
		this->callback(this);

	delete this;
	return series->pop();
}
```

这里不是callback后就立马delete了么

**Comment by Barenboim** [comment]
新的代码，server task的delete被延迟了，为了减少两个原子操作。你可以看看WFTask.inl里关于WFServerTask的实现。但无论内部什么时候调用delete，用户都应该认为callback之后任务就无效了。

**Comment by chanchann** [comment]
哦哦哦，我知道了，我忘记pull了，马上写个对比

**Comment by chanchann** [comment]
已经修改，添加了这个defer的对比

https://github.com/chanchann/workflow_annotation/blob/main/src_analysis/other_04_task_defer_delete.md
